<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ4g8d51\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ4g8d51/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerQ4g8d51.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerQ4g8d51\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerQ4g8d51\appProdProjectContainer([
    'container.build_hash' => 'Q4g8d51',
    'container.build_id' => 'b1ba293c',
    'container.build_time' => 1656101907,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ4g8d51');
