<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPsotas2\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPsotas2/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerPsotas2.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerPsotas2\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerPsotas2\appProdProjectContainer([
    'container.build_hash' => 'Psotas2',
    'container.build_id' => 'e0ed74a7',
    'container.build_time' => 1649767558,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPsotas2');
