<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAzjvxoi\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAzjvxoi/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerAzjvxoi.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerAzjvxoi\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerAzjvxoi\appDevDebugProjectContainer([
    'container.build_hash' => 'Azjvxoi',
    'container.build_id' => 'cc22ee47',
    'container.build_time' => 1656074940,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAzjvxoi');
